name: cloudflare staging

on:
  push:
    branches: ["production"]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - run: npx webpack
      - run: rm -rf node_modules
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=sailresults-production --commit-dirty=true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
